export const ADD_CONSRUCTOR_INGREDIENTS = 'ADD_ORDER_INGREDIENTS';
export const REMOVE_CONSRUCTOR_INGREDIENTS = 'REMOVE_ORDER_INGREDIENTS';
export const ADD_BUN_CONSRUCTOR = 'ADD_BUN_CONSRUCTOR';
export const MOVE_CONSRUCTOR_INGREDIENTS = 'MOVE_CONSRUCTOR_INGREDIENTS';
export const RESET_CONSRUCTOR_INGREDIENTS = 'RESET_CONSRUCTOR_INGREDIENTS';
